# Generated by Django 6.0.2 on 2026-05-06 02:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractivePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "target_company",
                    models.CharField(
                        blank=True,
                        help_text="Optional employer name. Used in closing paragraph and the optional employer section.",
                        max_length=120,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        blank=True, help_text="Optional role title. Used in closing paragraph.", max_length=200
                    ),
                ),
                (
                    "audience_focus",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("program_designer", "Program Experience Designer"),
                            ("lms_architect", "Learning Technology / LMS Architect"),
                            ("learning_engineer", "Learning Engineer"),
                            ("technical_id", "Technical Instructional Designer"),
                        ],
                        default="generic",
                        help_text="Default audience archetype when no ?role= query param is supplied.",
                        max_length=40,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#1A3A5C",
                        help_text="Hex colour driving the page's accent (e.g. #1A3A5C for Geotab).",
                        max_length=7,
                    ),
                ),
                (
                    "show_employer_section",
                    models.BooleanField(
                        default=False, help_text="Show the optional employer-specific section in the closing."
                    ),
                ),
                (
                    "chat_enabled",
                    models.BooleanField(
                        default=True, help_text="Wired up in Phase 3. Disable to hide the chat without removing data."
                    ),
                ),
                (
                    "hero_kicker",
                    models.CharField(
                        blank=True, help_text="Small uppercase label above the hero statement.", max_length=160
                    ),
                ),
                (
                    "hero_statement",
                    wagtail.fields.RichTextField(blank=True, help_text="The full-viewport opening statement."),
                ),
                (
                    "timeline_nodes",
                    wagtail.fields.StreamField(
                        [("timeline_node", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Year or short label (e.g. '2005' or '2024–25').", "max_length": 20},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Short headline for the node.", "max_length": 160},
                            ),
                            2: ("wagtail.blocks.RichTextBlock", (), {}),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("generic", "Generic"),
                                        ("program_designer", "Program Experience Designer"),
                                        ("lms_architect", "Learning Technology / LMS Architect"),
                                        ("learning_engineer", "Learning Engineer"),
                                        ("technical_id", "Technical Instructional Designer"),
                                    ]
                                },
                            ),
                            4: (
                                "wagtail.blocks.ListBlock",
                                (3,),
                                {
                                    "help_text": "Audience archetypes for which this node is most relevant. Used by the ?role= adaptation in Phase 2.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("year", 0), ("label", 1), ("body", 2), ("audience_tags", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "translation_rows",
                    wagtail.fields.StreamField(
                        [("translation_row", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "QlubPro side of the translation.", "max_length": 200},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Learning-platform equivalent.", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "One short paragraph on why the pattern transfers.", "required": False},
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Optional QlubPro screenshot shown when the row is expanded.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("qlubpro_feature", 0),
                                        ("learning_equivalent", 1),
                                        ("commentary", 2),
                                        ("screenshot", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "ai_cards",
                    wagtail.fields.StreamField(
                        [("ai_card", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 160}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            3: ("wagtail.blocks.CharBlock", (), {"max_length": 80, "required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("summary", 1), ("link", 2), ("link_label", 3)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "reflection",
                    wagtail.fields.StreamField(
                        [("reflection", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "The reflection question shown to the visitor."},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"max_length": 160}),
                            2: (
                                "wagtail.blocks.ListBlock",
                                (1,),
                                {"help_text": "Options the visitor can choose from."},
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("prompt", 0), ("options", 2)]], {}),
                        },
                    ),
                ),
                ("closing_paragraph", wagtail.fields.RichTextField(blank=True)),
                (
                    "chat_system_prompt",
                    models.TextField(blank=True, help_text="System prompt sent to the AI chat. Wired up in Phase 3."),
                ),
            ],
            options={
                "verbose_name": "Interactive page",
                "verbose_name_plural": "Interactive pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
