# Generated by Django 6.0.2 on 2026-05-06 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactivepage",
            name="accent_color",
            field=models.CharField(
                default="#1A3A5C",
                help_text="Six-digit hex colour driving the page's accent (e.g. #1A3A5C for Geotab). Injected into an inline style block — must be a valid hex value.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 6-digit hex colour with leading '#', e.g. #1A3A5C.", regex="^#[0-9A-Fa-f]{6}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="interactivepage",
            name="target_company",
            field=models.CharField(
                blank=True,
                help_text="Optional employer name. Rendered in the closing employer line only when 'Show employer section' is enabled.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="interactivepage",
            name="target_role",
            field=models.CharField(
                blank=True,
                help_text="Optional role title. Rendered in the closing employer line only when 'Show employer section' is enabled.",
                max_length=200,
            ),
        ),
    ]
