# Generated by Django 6.0.2 on 2026-05-06 15:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0002_alter_interactivepage_accent_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactivepage",
            name="translation_rows",
            field=wagtail.fields.StreamField(
                [("translation_row", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "QlubPro side of the translation.", "max_length": 200},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Learning-platform equivalent.", "max_length": 200},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "One short paragraph on why the pattern transfers.", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Optional QlubPro screenshot shown when the row is expanded.", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("generic", "Generic"),
                                ("program_designer", "Program Experience Designer"),
                                ("lms_architect", "Learning Technology / LMS Architect"),
                                ("learning_engineer", "Learning Engineer"),
                                ("technical_id", "Technical Instructional Designer"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "help_text": "Audience archetypes for which this row is most relevant. Used by the ?role= adaptation.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("qlubpro_feature", 0),
                                ("learning_equivalent", 1),
                                ("commentary", 2),
                                ("screenshot", 3),
                                ("audience_tags", 5),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
