# Generated by Django 6.0.2 on 2026-05-06 20:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0004_backfill_translation_row_audience_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactivepage",
            name="chat_starters",
            field=wagtail.fields.StreamField(
                [("starter", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.CharBlock", (), {"max_length": 160})},
                help_text="Guided starter questions shown as chips above the chat input. 4–6 recommended.",
            ),
        ),
    ]
