# Generated by Django 6.0.2 on 2026-05-06 23:57

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactive", "0005_interactivepage_chat_starters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interactivepage",
            name="chat_enabled",
            field=models.BooleanField(default=True, help_text="Disable to hide the chat without removing data."),
        ),
        migrations.AlterField(
            model_name="interactivepage",
            name="chat_system_prompt",
            field=models.TextField(blank=True, help_text="System prompt sent to the AI chat."),
        ),
        migrations.AlterField(
            model_name="interactivepage",
            name="timeline_nodes",
            field=wagtail.fields.StreamField(
                [("timeline_node", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Year or short label (e.g. '2005' or '2024–25').", "max_length": 20},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Short headline for the node.", "max_length": 160},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("generic", "Generic"),
                                ("program_designer", "Program Experience Designer"),
                                ("lms_architect", "Learning Technology / LMS Architect"),
                                ("learning_engineer", "Learning Engineer"),
                                ("technical_id", "Technical Instructional Designer"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "help_text": "Audience archetypes for which this node is most relevant. Drives the ?role= emphasis on render.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("year", 0), ("label", 1), ("body", 2), ("audience_tags", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
